// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Space-2]
	_ = x[Comment-3]
	_ = x[CommentBlock-4]
	_ = x[CommentLine-5]
	_ = x[Identifier-6]
	_ = x[String-7]
	_ = x[Number-8]
	_ = x[Semicolon-9]
	_ = x[Comma-10]
	_ = x[LParen-11]
	_ = x[RParen-12]
	_ = x[Plus-13]
	_ = x[Minus-14]
	_ = x[Asterisk-15]
	_ = x[Slash-16]
	_ = x[Typecast-17]
	_ = x[Add-18]
	_ = x[Alter-19]
	_ = x[By-20]
	_ = x[Cache-21]
	_ = x[Column-22]
	_ = x[Concurrently-23]
	_ = x[Constraint-24]
	_ = x[Create-25]
	_ = x[Default-26]
	_ = x[Exists-27]
	_ = x[Extension-28]
	_ = x[False-29]
	_ = x[Grant-30]
	_ = x[If-31]
	_ = x[Increment-32]
	_ = x[Index-33]
	_ = x[Insert-34]
	_ = x[Is-35]
	_ = x[Maxvalue-36]
	_ = x[Minvalue-37]
	_ = x[No-38]
	_ = x[Not-39]
	_ = x[Null-40]
	_ = x[On-41]
	_ = x[Only-42]
	_ = x[Owner-43]
	_ = x[Schema-44]
	_ = x[Select-45]
	_ = x[Sequence-46]
	_ = x[Set-47]
	_ = x[Start-48]
	_ = x[Table-49]
	_ = x[To-50]
	_ = x[True-51]
	_ = x[Unique-52]
	_ = x[Update-53]
	_ = x[Using-54]
	_ = x[Varying-55]
	_ = x[View-56]
	_ = x[With-57]
	_ = x[Zone-58]
	_ = x[Bigint-59]
	_ = x[Bigserial-60]
	_ = x[Boolean-61]
	_ = x[Bytea-62]
	_ = x[Character-63]
	_ = x[Date-64]
	_ = x[Integer-65]
	_ = x[Jsonb-66]
	_ = x[Numeric-67]
	_ = x[Serial-68]
	_ = x[Text-69]
	_ = x[Timestamp-70]
	_ = x[Time-71]
	_ = x[Tsvector-72]
}

const _TokenType_name = "IllegalEOFSpaceCommentCommentBlockCommentLineIdentifierStringNumberSemicolonCommaLParenRParenPlusMinusAsteriskSlashTypecastAddAlterByCacheColumnConcurrentlyConstraintCreateDefaultExistsExtensionFalseGrantIfIncrementIndexInsertIsMaxvalueMinvalueNoNotNullOnOnlyOwnerSchemaSelectSequenceSetStartTableToTrueUniqueUpdateUsingVaryingViewWithZoneBigintBigserialBooleanByteaCharacterDateIntegerJsonbNumericSerialTextTimestampTimeTsvector"

var _TokenType_index = [...]uint16{0, 7, 10, 15, 22, 34, 45, 55, 61, 67, 76, 81, 87, 93, 97, 102, 110, 115, 123, 126, 131, 133, 138, 144, 156, 166, 172, 179, 185, 194, 199, 204, 206, 215, 220, 226, 228, 236, 244, 246, 249, 253, 255, 259, 264, 270, 276, 284, 287, 292, 297, 299, 303, 309, 315, 320, 327, 331, 335, 339, 345, 354, 361, 366, 375, 379, 386, 391, 398, 404, 408, 417, 421, 429}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
