// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Space-2]
	_ = x[Comment-3]
	_ = x[CommentBlock-4]
	_ = x[CommentLine-5]
	_ = x[Identifier-6]
	_ = x[String-7]
	_ = x[Number-8]
	_ = x[Dot-9]
	_ = x[Semicolon-10]
	_ = x[Comma-11]
	_ = x[LParen-12]
	_ = x[RParen-13]
	_ = x[Equal-14]
	_ = x[Plus-15]
	_ = x[Minus-16]
	_ = x[Asterisk-17]
	_ = x[Slash-18]
	_ = x[Typecast-19]
	_ = x[Add-20]
	_ = x[Alter-21]
	_ = x[Asc-22]
	_ = x[By-23]
	_ = x[Cache-24]
	_ = x[Column-25]
	_ = x[Concurrently-26]
	_ = x[Constraint-27]
	_ = x[Create-28]
	_ = x[Database-29]
	_ = x[Default-30]
	_ = x[Desc-31]
	_ = x[Exists-32]
	_ = x[Extension-33]
	_ = x[False-34]
	_ = x[Function-35]
	_ = x[Grant-36]
	_ = x[If-37]
	_ = x[Increment-38]
	_ = x[Index-39]
	_ = x[Insert-40]
	_ = x[Is-41]
	_ = x[Maxvalue-42]
	_ = x[Minvalue-43]
	_ = x[No-44]
	_ = x[Not-45]
	_ = x[Null-46]
	_ = x[On-47]
	_ = x[Only-48]
	_ = x[Operator-49]
	_ = x[Owner-50]
	_ = x[Revoke-51]
	_ = x[Role-52]
	_ = x[Schema-53]
	_ = x[Select-54]
	_ = x[Sequence-55]
	_ = x[Set-56]
	_ = x[Start-57]
	_ = x[Table-58]
	_ = x[To-59]
	_ = x[Trigger-60]
	_ = x[True-61]
	_ = x[Unique-62]
	_ = x[Update-63]
	_ = x[Using-64]
	_ = x[Varying-65]
	_ = x[View-66]
	_ = x[With-67]
	_ = x[Zone-68]
	_ = x[Bigint-69]
	_ = x[Bigserial-70]
	_ = x[Boolean-71]
	_ = x[Bytea-72]
	_ = x[Character-73]
	_ = x[Date-74]
	_ = x[Integer-75]
	_ = x[Jsonb-76]
	_ = x[Numeric-77]
	_ = x[Serial-78]
	_ = x[Text-79]
	_ = x[Timestamp-80]
	_ = x[Time-81]
	_ = x[Tsvector-82]
}

const _TokenType_name = "IllegalEOFSpaceCommentCommentBlockCommentLineIdentifierStringNumberDotSemicolonCommaLParenRParenEqualPlusMinusAsteriskSlashTypecastAddAlterAscByCacheColumnConcurrentlyConstraintCreateDatabaseDefaultDescExistsExtensionFalseFunctionGrantIfIncrementIndexInsertIsMaxvalueMinvalueNoNotNullOnOnlyOperatorOwnerRevokeRoleSchemaSelectSequenceSetStartTableToTriggerTrueUniqueUpdateUsingVaryingViewWithZoneBigintBigserialBooleanByteaCharacterDateIntegerJsonbNumericSerialTextTimestampTimeTsvector"

var _TokenType_index = [...]uint16{0, 7, 10, 15, 22, 34, 45, 55, 61, 67, 70, 79, 84, 90, 96, 101, 105, 110, 118, 123, 131, 134, 139, 142, 144, 149, 155, 167, 177, 183, 191, 198, 202, 208, 217, 222, 230, 235, 237, 246, 251, 257, 259, 267, 275, 277, 280, 284, 286, 290, 298, 303, 309, 313, 319, 325, 333, 336, 341, 346, 348, 355, 359, 365, 371, 376, 383, 387, 391, 395, 401, 410, 417, 422, 431, 435, 442, 447, 454, 460, 464, 473, 477, 485}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
