// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Space-2]
	_ = x[Comment-3]
	_ = x[CommentBlock-4]
	_ = x[CommentLine-5]
	_ = x[Identifier-6]
	_ = x[String-7]
	_ = x[Number-8]
	_ = x[Semicolon-9]
	_ = x[Comma-10]
	_ = x[LParen-11]
	_ = x[RParen-12]
	_ = x[Plus-13]
	_ = x[Minus-14]
	_ = x[Asterisk-15]
	_ = x[Slash-16]
	_ = x[Typecast-17]
	_ = x[Add-18]
	_ = x[Alter-19]
	_ = x[By-20]
	_ = x[Cache-21]
	_ = x[Column-22]
	_ = x[Constraint-23]
	_ = x[Create-24]
	_ = x[Default-25]
	_ = x[Extension-26]
	_ = x[False-27]
	_ = x[Grant-28]
	_ = x[Increment-29]
	_ = x[Index-30]
	_ = x[Insert-31]
	_ = x[Maxvalue-32]
	_ = x[Minvalue-33]
	_ = x[No-34]
	_ = x[Not-35]
	_ = x[Null-36]
	_ = x[On-37]
	_ = x[Only-38]
	_ = x[Owner-39]
	_ = x[Schema-40]
	_ = x[Select-41]
	_ = x[Sequence-42]
	_ = x[Set-43]
	_ = x[Start-44]
	_ = x[Table-45]
	_ = x[To-46]
	_ = x[True-47]
	_ = x[Update-48]
	_ = x[Using-49]
	_ = x[Varying-50]
	_ = x[With-51]
	_ = x[Zone-52]
	_ = x[Bigint-53]
	_ = x[Bigserial-54]
	_ = x[Boolean-55]
	_ = x[Bytea-56]
	_ = x[Character-57]
	_ = x[Date-58]
	_ = x[Integer-59]
	_ = x[Jsonb-60]
	_ = x[Numeric-61]
	_ = x[Serial-62]
	_ = x[Text-63]
	_ = x[Timestamp-64]
	_ = x[Time-65]
	_ = x[Tsvector-66]
}

const _TokenType_name = "IllegalEOFSpaceCommentCommentBlockCommentLineIdentifierStringNumberSemicolonCommaLParenRParenPlusMinusAsteriskSlashTypecastAddAlterByCacheColumnConstraintCreateDefaultExtensionFalseGrantIncrementIndexInsertMaxvalueMinvalueNoNotNullOnOnlyOwnerSchemaSelectSequenceSetStartTableToTrueUpdateUsingVaryingWithZoneBigintBigserialBooleanByteaCharacterDateIntegerJsonbNumericSerialTextTimestampTimeTsvector"

var _TokenType_index = [...]uint16{0, 7, 10, 15, 22, 34, 45, 55, 61, 67, 76, 81, 87, 93, 97, 102, 110, 115, 123, 126, 131, 133, 138, 144, 154, 160, 167, 176, 181, 186, 195, 200, 206, 214, 222, 224, 227, 231, 233, 237, 242, 248, 254, 262, 265, 270, 275, 277, 281, 287, 292, 299, 303, 307, 313, 322, 329, 334, 343, 347, 354, 359, 366, 372, 376, 385, 389, 397}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
